"use client";
import Link from "next/link";
import { useState } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout_main() {
  const [hidden, setHidden] = useState(true);
  const onClick = (event: any) => {
    setHidden(!hidden);
  };
  return (
    <>
      <button
        className="bg-red-700 text-yellow-400 w-[100px] border-x-8 border-gray-400 m-3"
        onClick={onClick}
      >
        menu
      </button>
      <div className={hidden ? "hidden" : ""}>
        <h1 className="flex justify-center font-bold text-3xl my-10">
          빨강의 Nextjs Room
        </h1>
        <div className="ml-40 mr-40 text-center py-5 border-y-2 ">
          <div className="flex justify-between mx-10">
            <Link className="bg-red-400 w-[200px]" href="/">
              home
            </Link>
            <Link className="bg-red-400 w-[200px]" href="/todo">
              todo
            </Link>
            <Link className="bg-red-400 w-[200px]" href="/coin">
              coin
            </Link>
            <Link className="bg-red-400 w-[200px]" href="/movie">
              movie
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
